server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.141:3306/house?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: springcloud-server
  data:


