server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: house-feign
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
